// 
// Copyright (c) 2013 Agustin Santos
// 
// Permission is hereby granted, free of charge, to any person obtaining a 
// copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation 
// the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included 
// in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
// DEALINGS IN THE SOFTWARE.
//

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibNoise.Models
{
    /// Model that defines the surface of a cylinder.
    ///
    /// @image html modelcylinder.png
    ///
    /// This model returns an output value from a noise module given the
    /// coordinates of an input value located on the surface of a cylinder.
    ///
    /// To generate an output value, pass the (angle, height) coordinates of
    /// an input value to the GetValue() method.
    ///
    /// This model is useful for creating:
    /// - seamless textures that can be mapped onto a cylinder
    ///
    /// This cylinder has a radius of 1.0 unit and has infinite height.  It is
    /// oriented along the @a y axis.  Its center is located at the origin.
    public class Cylinder
    {
        /// Constructor.
        public Cylinder()
        {
            m_pModule = null;
        }

        /// Constructor
        ///
        /// @param module The noise module that is used to generate the output
        /// values.
        public Cylinder(ModuleBase module)
        {
            m_pModule = module;
        }

        /// Returns the noise module that is used to generate the output
        /// values.
        ///
        /// @returns A reference to the noise module.
        ///
        /// @pre A noise module was passed to the SetModule() method.
        public ModuleBase GetModule()
        {
            Debug.Assert(m_pModule != null);
            return m_pModule;
        }

        /// Returns the output value from the noise module given the
        /// (angle, height) coordinates of the specified input value located
        /// on the surface of the cylinder.
        ///
        /// @param angle The angle around the cylinder's center, in degrees.
        /// @param height The height along the @a y axis.
        ///
        /// @returns The output value from the noise module.
        ///
        /// @pre A noise module was passed to the SetModule() method.
        ///
        /// This output value is generated by the noise module passed to the
        /// SetModule() method.
        ///
        /// This cylinder has a radius of 1.0 unit and has infinite height.
        /// It is oriented along the @a y axis.  Its center is located at the
        /// origin.
        public double GetValue(double angle, double height)
        {
            Debug.Assert(m_pModule != null);

            double x, y, z;
            x = Math.Cos(Utils.DegToRad * angle);
            y = height;
            z = Math.Sin(Utils.DegToRad * angle);
            return m_pModule.GetValue(x, y, z);
        }

        /// Sets the noise module that is used to generate the output values.
        ///
        /// @param module The noise module that is used to generate the output
        /// values.
        ///
        /// This noise module must exist for the lifetime of this object,
        /// until you pass a new noise module to this method.
        public void SetModule(ModuleBase module)
        {
            m_pModule = module;
        }

        /// A pointer to the noise module used to generate the output values.
        private ModuleBase m_pModule;

    }
}
